/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mycompany_app_App */

#ifndef _Included_com_mycompany_app_App
#define _Included_com_mycompany_app_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mycompany_app_App
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mycompany_app_App_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_mycompany_app_App
 * Method:    connect
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mycompany_app_App_connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mycompany_app_App
 * Method:    send
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mycompany_app_App_send
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mycompany_app_App
 * Method:    receive
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mycompany_app_App_receive
  (JNIEnv *, jobject);

/*
 * Class:     com_mycompany_app_App
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mycompany_app_App_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
